### ISSUE TITLE
SDA crashes with Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Joltrix** [Starcounter/DevTools#66] opened 2018-01-08 14:42 UTC
Currently there is no steps to reproduce, only a stack trace:

```
Uncaught RangeError: Maximum call stack size exceeded
    at H (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at W (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at Sa.walk (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at new Sa (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at H (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at W (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at Sa.walk (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at new Sa (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at H (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
    at Sa.observeArray (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/ui-popup-build.js:1)
chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4 Uncaught RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at i.updateListener (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at o (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at updateListeners.forEach (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at Array.forEach (<anonymous>)
    at Object.createRow (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at Object.onPatchSent (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at HTMLElement.fire (legacy-element-mixin.html:376)
    at HTMLElement.onPatchSent (palindrom-client.html:269)
    at w.send (palindrom-dom.min.js:2)
2chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4 Uncaught RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at i.updateListener (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at o (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at updateListeners.forEach (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at Array.forEach (<anonymous>)
    at Object.createRow (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at Object.onPatchReceived (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at HTMLElement.fire (legacy-element-mixin.html:376)
    at HTMLElement.onPatchReceived (palindrom-client.html:262)
    at e.handleRemoteChange (palindrom-dom.min.js:2)
3chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4 Uncaught RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at i.updateListener (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at o (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at updateListeners.forEach (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at Array.forEach (<anonymous>)
    at Object.createRow (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at Object.onPatchSent (chrome-extension://mpchkilmmalfopikamgellgdgoidhmnh/injected_script.js:4)
    at HTMLElement.fire (legacy-element-mixin.html:376)
    at HTMLElement.onPatchSent (palindrom-client.html:269)
    at w.send (palindrom-dom.min.js:2)
injected_script.js:4 Uncaught RangeError: Maximum call stack size exceeded
    at JSON.stringify (<anonymous>)
    at i.updateListener (injected_script.js:4)
    at o (injected_script.js:4)
    at updateListeners.forEach (injected_script.js:4)
    at Array.forEach (<anonymous>)
    at Object.createRow (injected_script.js:4)
    at Object.onPatchSent (injected_script.js:4)
    at HTMLElement.fire (legacy-element-mixin.html:376)
    at HTMLElement.onPatchSent (palindrom-client.html:269)
    at w.xhr (palindrom-dom.min.js:sourcemap:2)
```

![image](https://user-images.githubusercontent.com/10708580/34675638-85e3dc6a-f48a-11e7-97e1-abaf1faadadc.png)

cc @miyconst

**Comment by alshakero** [comment] 2018-01-08 14:46
Thanks for reporting Dimitris! I'm looking at it. I think this is a duplicate of https://github.com/Starcounter/DevTools/issues/65.

**Comment by alshakero** [comment] 2018-01-08 23:57
Fixed in https://github.com/Starcounter/DevTools/commit/e6c4cc3df5592d128b6e5f1a16ee075f241dc4d6. Poor Vue was filter through 14.5K duplicated imports.

Released 3.1.0 for FF and Chrome. You should see it in your browser automatically by the morning. If the issue presists please make sure you're running 3.1.0, if it still persists even in 3.1.0 feel free to reopen this issue.

**Comment by warpech** [comment] 2018-01-09 12:37
Is this normal that one app has 14.5K duplicated imports? I would expect hundreds, but not tens of thousands.... Did you evaluate why are there so many imports?

**Comment by Joltrix** [comment] 2018-01-09 12:45
Im not sure if this is the same problem, but I am noticing some major lag issues when I have the debug aid open and try to navigate on a page

![laaag](https://user-images.githubusercontent.com/10708580/34721475-2c3ec0da-f543-11e7-8502-886f653e52a6.gif)
(I have the debug aid in "Pop out" mode & have the Patches tab open)

If I close the debug aid, the lag disappears completely.
@alshakero Should I reopen this issue, or create a new one?

**Comment by warpech** [comment] 2018-01-09 14:07
@Joltrix I guess it is fair to ask what is the version of DevTools that you have?

**Comment by miyconst** [comment] 2018-01-09 14:18
Today Heads also reported "major lags and hangs"  for SDA, unfortunately without anything specific.

**Comment by alshakero** [comment] 2018-01-09 14:23
Yes they're were a big motivation to release 3.1.0. Could you notify them about it? Even though Chrome and FF should do it auto.

**Comment by Joltrix** [comment] 2018-01-09 14:46
@warpech 
I'm using 3.1.0, as @alshakero said, it updated automatically without me having to do anything.

The only "sure way" of reproducing it that I know of is to open the debug aid as a pop out, open the patches tab, and leave it open, and then just click around on the page. on buttons / links / tabs etc. within a few seconds, it will start to lag

**Comment by warpech** [comment] 2018-01-15 16:56
@alshakero did you manage to reproduce it?

**Comment by alshakero** [comment] 2018-01-20 00:39
@warpech 

Well yes, but it's I would say it's simply DevTools is rerendering a lot of stuff when the model mutates upon navigation. So I'm not sure if this is a bug or just bad performance that needs some enhancements that kinda take time. 

@Joltrix is it just toleratable or downright useless? If it's the latter I can kill it with enough focus like the imports dupes thing. If it's toleratable I think we can focus of other stuff.

**Comment by Joltrix** [comment] 2018-01-22 08:11
@alshakero Well, I haven't been using it that much as of late, but the times I've used it, I've managed to get the job done ;), So as you said, I think we can focus on other stuff and improve the debug aid at a later date :)

**Comment by alshakero** [comment] 2018-01-23 13:25
I think I'll close this for the mean time then. Since it's not a bug or a failure. I have perf enhancements as a constant goal and this will get better with time.

**Closed by alshakero** 2018-01-23 13:25 UTC
